# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
            - name: Download a Build Artifact
  uses: actions/download-artifact@v3.1.0
  with:
    # Artifact name
    name: # optional
    # Destination path
    path: # optional
          
            - name: Docker Build Tag Publish to ECR
  # You may pin to the exact commit or the version.
  # uses: bitovi/github-actions-docker-ecr-publish@bcaf3fb11bafbc6ae884516e92f870ac11a5ae68
  uses: bitovi/github-actions-docker-ecr-publish@v0.1.0
  with:
    # Checkout the repository
    checkout: # optional, default is true
    # Use action builtin login
    aws_login: # optional, default is true
    # AWS access key ID
    aws_access_key_id: 
    # AWS secret access key
    aws_secret_access_key: 
    # AWS session token
    aws_session_token: # optional
    # AWS default region
    aws_default_region: # optional, default is us-east-1
    # AWS ECR repository name. e.g. hello-repository
    aws_ecr_repo_name: 
    # Tag to override default Logic
    image_tag: # optional, default is 
    # Use the SHA for the tag.  Overrides the default logic.
    use_sha: # optional
    # Docker org name.
    org_name: # optional, default is 
    # Tag default branch with latest tag instead of branch name.
    use_latest: # optional, default is true
    # Add a string of values to the end of the build command
    build_args: # optional
    # Specify the working directory that the docker build will be run in
    working_directory: # optional
          
